title: Jason Wei
description: AI Researcher
theme: null
baseurl: ""
url: "https://JasonWei05.github.io"

social_links:
  x: https://x.com/jaswwei
  linkedin: https://www.linkedin.com/in/jason-w-wei/

collections:
  reviews:
    output: true
    permalink: /reviews/:slug/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "reviews"
    values:
      layout: "post"

markdown: kramdown
